export const FETCH_CHARACTERS_PENDING = "FETCH_CHARACTERS_PENDING";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR";
export const FILTER_BY_VALUE = "FILTER_BY_VALUE";
